//Global Variables
global.REQUEST_SUCCESS = 200;
global.REQUEST_FAILED = 400;
global.REQUEST_UNAUTHORIZED = 403;
global.REQUEST_INTERNAL_ERROR = 500;
global.REQUEST_BLOCKED = 450;

global.DATABASE_ERROR = "DATABASE_ERROR: ";
